# Analyse de langage naturel 

**Et si une simple application pouvait détecter si vos commentaires en
ligne sont positifs ou négatifs, tout en restant 100% fiable et
éthique ?**

Conception d'un programme permettant à partir de phrases (par exemple)
entrées par un utilisateur d'exprimer si elles sont positives ou
négatifs (par exemple des commentaires en ligne). Cela fait aussi appel
à des enjeux éthiques (ne pas biaiser le programme pour diffuser de
fausses informations) et mathématiques (statistiques, algorithmes de knn
...) pour la conception du programme. Des notions en HTML peuvent être
vues pour implémenter cette solution en un site web.

::: {.small data-latex=""}
|                        |                                            |
| :------------- | :----------------------------------------- |
| Référent·e·(s)         | _M. Aurélien Saudemont et M. Mourad Ahmane_                              |
| Répartition des élèves | Indifférent                                |
| Présentation en salle  | 346                                  |
:::