# Composition et Réalisation d'un EP / Clip vidéo musical

L'objectif de ce TM est de réaliser un EP à partir de compositions
musicales personnelles. Vous aurez également l'opportunité de créer un
clip vidéo pour illustrer l'une de vos compositions.

Le TM s'effectue en trois étapes : 

**La composition**
Dans un premier temps, vous devrez composer la musique et les paroles
(s'il y en a) de votre EP. Ces compositions pourront être faites dans
n'importe quel style musical (chanson française, rap, pop,
classique,...).

**L'enregistrement**
Vous devrez ensuite vous occuper de l'instrumentation et de
l'enregistrement de vos compositions en utilisant les logiciels audios
tels que logic pro X, Ableton, Garageband, Pro Tools et réaliser un mix
puis un Mastering. Vous pourrez vous entourer d'autres musiciens si vous
le jugez nécessaire.

**Réalisation du clip**
Enfin, vous devrez présenter un clip vidéo pour illustrer une de vos
compositions. Pour cela, vous devrez utiliser un logiciel d'édition
vidéo.

Dans le travail écrit, vous présenterez vos compositions (accords,
paroles ou partitions) ainsi que les différentes techniques de
composition, d'enregistrement, d'éditions musicales et vidéos que vous
aurez acquises durant tout le processus.

::: {.small data-latex=""}
|                        |                                            |
| :------------- | :----------------------------------------- |
| Référent·e·(s)         | _M. François Voeffray_                              |
| Répartition des élèves | Indifférent                                |
| Présentation en salle  | 310                                  |
:::