# Composition et Réalisation d'un EP / clip vidéo musical

L'objectif de ce TM est de réaliser un EP à partir de compositions musicales personnelles. Puis vous pourrez réaliser un clip musical à partir de vos compositions.

Dans un premier temps, vous devrez composer la musique et les paroles de votre EP. Ces compositions pourront être faites dans n'importe quel style musical (chanson française, rap, pop, classique,…). Vous devrez vous occuper de l'instrumentation et de l'enregistrement de votre composition en utilisant les logiciels audios (logic pro X, Ableton, Garageband, Pro Tools) pour en réaliser un mix et un Mastering. Vous pourrez vous entourer d'autres musiciens si vous le jugez nécessaire. Enfin, vous devrez présenter un petit clip vidéo pour illustrer une de vos compositions. Vous devrez utiliser un logiciel d'édition vidéo pour la réalisation de celui-ci.

Dans la travail écrit, vous présenterez vos compositions ainsi que les différentes techniques d'édition musicales et vidéo que vous aurez acquises durant tout le processus.

::: {.signature data-latex=""}
*François Voeffray*
:::