# Créez votre propre film d’animation ou votre premier objet 3D avec Blender

**Prêt à faire vos premiers pas dans le cinéma numérique ou l'impression
3D ?**

Explorer l'univers fascinant de l'animation ou l'impression 3D, à
l'image de grandes productions dans le cinéma. Sans pour autant vouloir
atteindre la puissance des industries, et grâce à Blender, un logiciel
de création 3D gratuit et intuitif, il est possible de réaliser un court
métrage d'animation original, des pièces de costume ou bien même un
décor. Le but est de fabriquer et de documenter de A à Z une animation
de quelques minutes ou une pièce imprimable en 3D (par exemple : deux
personnages se rencontrent et se serrent la main, l'éclosion d'une
fleur imaginaire, création d'un petit objet de décor, accessoire de
costumes, etc.). Au fil de ce travail, vous apprendrez les bases de
l'animation 3D et documenterez chaque étape de la création de votre
production. << 

::: {.small data-latex=""}
|                        |                                            |
| :------------- | :----------------------------------------- |
| Référent·e·(s)         | _M. Mourad Ahmane_                              |
| Répartition des élèves | Indifférent                                |
| Présentation en salle  | 320                                  |
:::