# Ecritures d'artistes, histoire d'écritures : \linebreak évolutions et appropriations de l'écriture

En 1451, l'homo sapiens d'Europe commençait à imprimer. L'invention de la presse à caractères mobiles permit une double démocratisation, celle de la fabrication de livres et celle de la lecture. L'ancêtre de votre bande-dessinée de Garfield, de votre vocabulaire d'allemand, de vos poèmes de Baudelaire et de vos mangas, c'était un tout premier livre imprimé par Johannes Gutenberg : la grammaire latine de Donatus. 

La fabrication d'un livre, même d'un petit livre, nécessite un contenu, donc des images et du texte. Et si c'était à vous de créer un livre ? À l'aide d'outils d'impression anciens et modernes, seriez-vous capables de créer un livre unique ? 

::: {.signature data-latex=""}
_Nathalie Fischli_
:::

***

L'histoire commence avec l'écriture. Cunéiforme, Arial, onciale ou caroline, majuscule ou minuscule, l'écriture évolue et se transforme. Elle s'adapte, elle crée des révolutions. Avec l'apparition de l'imprimerie, les mœurs sont bouleversées. Et presque six cents ans plus tard, à l'heure du numérique, l'écriture manuscrite tend à disparaître. 

Ici, vous écrirez sur l'histoire de l'écrit. Pourquoi écrire ? Pourquoi imprimer ? Qui écrit ? Quelles informations méritent-elles de passer à la postérité ? Voici des questions sur lesquelles votre plume (ou votre clavier) pourrait disserter. 

::: {.signature data-latex=""}
_Pauline Meylan_
:::

Travail en binôme recommandé.