# Journaux (littérature personnelle)

Au fur et à mesure de l'histoire littéraire, les formes d'écriture de soi ont revêtu une myriade de formes différentes : mémoires, autobiographies, autofictions, carnets, journaux intimes, etc. Dans tous les cas, il s'agit de s'exposer, de mettre en lumière un parcours, ponctuel (pensées du jour) ou diachronique (sur une partie ou l'ensemble d'une vie). Certaines de ces écritures de soi sont résolument personnelles, en témoignent les cadenas autour de certains carnets, d'autres, au contraire, s'adressent à un certain public pour qu'il ait accès à l'ensemble des rouages qui ont gouverné une vie.

Et s'il était possible de rendre accessibles les pensées d'un personnage historique (Napoléon, Jésus, etc.) ou d'un personnage de fiction (Captain America, Aragorn, etc.) ? Dans ce travail, il s'agira de donner quelques éléments théoriques de l'écriture de soi, quelques éléments saillants qui reviennent systématiquement dans l'exposition de soi, dans un premier temps.

Dans un deuxième temps, il s'agira de sélectionner un personnage emblématique et de coucher sur le papier les pensées, dilemmes, interrogations qu'il aurait dû avoir à un moment de sa vie…

Ce travail se veut créatif, et, hormis la contrainte de l'écriture de soi (ici, l'écriture d'un autre soi, imaginaire et fantasmé), l'élève est libre de choisir un personnage réel ou fictif et de rédiger un ensemble de pensées originales qui auraient pu survenir sous la plume dudit personnage.

::: {.signature data-latex=""}
_Pierre Bonjour_
:::