# Philosophie de l'art :  La beauté et la vérité

Que la beauté soit une affaire de goût, qu'elle soit subjective, qu'elle soit relative et propre à chacun, c'est ce qui semble aller de soi. Mais que dire du chef-d'œuvre qui prétend à l'universalité\ ? Que dire du jugement esthétique qui s'offusque lorsqu'on le contrarie\ ? Une fleur est belle, un paysage est beau, un visage est beau\ : n'est-ce pas à dire que la beauté se situe dans les choses\ ? Qu'elle est objective\ ? Mais alors, comment se dévoile-t-elle\ ? Est-ce par une modification du regard chez l'observateur, par un travail de l'artiste sur la chose qu'il façonne, ou par l'éclat à peine aperçu d'un objet qui suggère qu'il dissimule un secret\ ? Pouvons-nous nous contenter de regarder une œuvre d'art ou devons-nous la contempler\ ? Et l'artiste, dès lors, est-il un créateur ou un voyant\ ? Il n'est pas rare d'ailleurs que nous ressentions un sentiment d'authenticité face à une œuvre d'art –\ comme si là, en face de nous, c'était la vérité qui s'exprimait. Ce sentiment équivaut-il à une émotion\ ? Une réaction à une réalité qui donne des frissons\ ? Mais si c'est la vérité qui se manifeste dans une œuvre d'art\ – est-ce à dire que la science ne possède pas le monopole du savoir\ ? Que la science et l'art seraient des disciplines opposées, voire incompatibles\ ? Rien n'est moins sûr. Mais nous entendons que l'art a pour fonction d'imiter la nature, alors que la science l'explique et la décrit. Ne serait-ce pas que l'art a pour fonction d'embellir la nature\ ? Mais que dire alors des œuvres sublimes qui accentuent la laideur physique et la dégradation morale de ses sujets\ ? Que dire des caricatures, par exemple, desquelles se dégagent indiscutablement une modalité du beau et du vrai\ ? Accentuer les traits, déformer les corps, exagérer les expressions\ : n'est-ce pas mentir\ ? Que dire des dissonances musicales qui semblent rompre un ordre harmonique qui est si doux à nos oreilles\ ? Représenter iconographiquement des êtres célestes et divins, n'est-ce pas profaner des entités qui dépassent la condition de l'homme\ ? Très rapidement s'est posée la question de savoir comment exprimer une idée artistique.

Nous pourrions en outre nous demander si l'expression artistique est une activité proprement humaine. Ne voyons-nous pas des araignées construire des édifices symétriques, dont la régularité surpassent parfois nos efforts architecturaux\ ? N'observons-nous pas dans la nature de nombreux actes de séduction animalière qui laissent entendre que les animaux possèdent aussi une sensibilité esthétique ? Peut-être que l'harmonie de la nature nous a conféré des normes artistiques dont il est difficile de nous défaire.

Tel serait un échantillon des questions qui peuvent être soulevées dans ce Travail de Maturité. Avec l'aide de textes appartenant à la tradition philosophique, mais aussi à la littérature, à la poésie, et aux artistes eux-mêmes –\ qui ont souvent écrit sur leur pratique\ –, nous nous interrogerons sur l'attrait qu'exerce sur nous le pouvoir des créations artistiques. Qu'il s'agisse du plaisir indescriptible qu'éveille la jouissance artistique, du moment de suspens que provoque en nous l'expérience esthétique elle-même, du basculement par lequel nous nous perdons dans un tableau, dans une sculpture, dans un morceau de musique, ou dans un film, du sérieux ou du jeu avec lesquels nous nous approchons d'une œuvre d'art, du milieu dans lequel l'œuvre d'art doit ou peut être appréhendée (théâtre, musée, chez soi, nature), de la modification que lui fait subir les impératifs de consommation, nous nous attacherons à montrer que la création artistique possède une place fondamentale dans notre rapport au monde.

Ce Travail de Maturité est ouvert à tous et n'exige aucun prérequis. Il demande simplement un intérêt pour la question artistique, une envie de penser, et une dose de curiosité.

::: {.signature data-latex=""}
*Jeremy Filthuth et Esma Puric*
:::
