# Réalité et fiction

> *When we read dystopia, we root for these people to break free because
> we are these people; hoping and fighting against things that are bigger
> than ourselves.*  
> *--Ally Condie*

Utiliser la fiction pour raconter, dénoncer ou encore encenser une
réalité est un processus littéraire commun, une manière de raconter
l'Histoire. Orwell, Atwood et bien d'autres ont dénoncé des sociétés
totalitaires sous le couvert de la dystopie.

Le réalisme merveilleux, quant à lui, introduit des aspects magiques
dans le banal. Genre associé à la littérature latino-américaine, il a su
transfigurer des réalités trop douloureuses à accepter ou encore a
permis de réécrire l'Histoire en redonnant une voix aux marginaux qui
d'habitude ne sont pas entendus.

Autrices et auteurs issu.e.s de la migration ont transmis leurs
expériences, leurs espoirs, illustrant ainsi, par leur témoignage, une
nouvelle réalité: celle du déracinement et de l'entre-deux.

Analyser le rapport entre la fiction et la réalité permet d'explorer les
liens entre l'individu et le collectif : comment une histoire peut-elle
raconter des histoires, comment celles-ci peuvent-elles éclairer
l'Histoire ? Par exemple, l'expérience de la migration est souvent
singulière et pourtant il y a un aspect universel à chacun de ces
récits. Comment leurs histoires, leurs récits, biographiques ou non,
permettent-ils d'éclairer les pendants de la Grande Histoire ?

La fiction, dans son ensemble, s'inspire de topoï historiques. Comment
ces liens sont-ils réalisés ? La fiction peut-elle avoir également un
impact sur la réalité ? La fiction peut-elle soigner la réalité ? Au
travers de ce travail de maturité, vous analyserez une œuvre littéraire
dans le but de mettre en avant les liens qui se jouent entre la réalité
et la fiction, ce que l'un raconte de l'autre.

\clearpage

Ce travail peut être rédigé en français ou en anglais.

Possibles œuvres à explorer :

-   Aldous Huxley, Brave New World (Le Meilleur des Mondes)
-   Annie Ernaux, Mémoire de fille
-   Arundathi Roy, The God of Small Things (Le Dieu des Petits Riens) 
-   Pierre Michon, Vies Minuscules
-   Suzanne Collins, The Hunger Games 
-   Junot Diaz, The Brief Wondrous Life of Oscar Wao (La brève et
    mystérieuse vie d'Oscar Wao)

::: {.signature data-latex=""}
_Mme Somanadan_  
_Mme Meylan_  
:::

Répartition des élèves : Binômes conseillés