# Objectifs et évaluation {-}

\vspace{\stretch{1}}

## Principes fondamentaux {-}

Le travail de maturité est l'occasion pour l'élève, à l'issue d'un processus de longue durée, de parvenir à une assise, une "maturité" intellectuelle suffisamment solide pour pouvoir produire un discours ou une œuvre qu'il peut assumer en tant qu'auteur et soumettre au regard d'autrui. En d'autres termes, il s'agit pour lui de se constituer comme sujet d'une énonciation.

\vspace{\stretch{1}}

## Objectifs fondamentaux {-}

Fondamentalement, il doit, pour parvenir à cela, être capable de :

- mener une recherche documentaire de qualité ;
- structurer sa pensée, afin de progresser vers un but, qui consiste à résoudre un problème ;
- formuler sa pensée pour la rendre intelligible à autrui ;
- évaluer sa propre démarche et distinguer clairement sa position personnelle d'autres points de vue, en justifiant ses choix.

\vspace{\stretch{1}}

\clearpage

\vspace*{\stretch{1}}

## Évaluation {-}

### Relation pédagogique {-}

Le travail de maturité s'élabore sous la conduite d'un maître répondant. Il s'agit d'un processus de longue durée, qui doit être considéré comme une situation d'enseignement, ce qui implique un suivi et des échanges réguliers entre le répondant et l'élève.

En entreprenant son travail de maturité, l'élève s'engage dans une relation de collaboration avec son répondant : cela suppose que le contact soit cultivé de part et d'autre.

### Évaluation {-}

L'évaluation du travail de maturité (travail d'analyse ou de création) porte sur les six domaines de compétence suivants :

- Recherche et méthodes de travail
- Contenu et sens
- Structure de l'opuscule
- Sens critique, lucidité sur son travail
- Expression
- Présentation

\vspace{\stretch{1}}