# Rappel des dispositions règlementaires {-}

### Règlement du 16 janvier 1995 sur la reconnaissance des certificats de maturité gymnasiale (RRM) {-}
_[édicté par la Conférence suisse des Directeurs cantonaux de l'instruction publique (CDIP) ; état au 1er août 2007]_

\vspace{\stretch{1}}

_Art. 9 Disciplines de maturité_

1. Les disciplines fondamentales, l'option spécifique, l'option complémentaire et le travail de maturité constituent l'ensemble des disciplines de la maturité.

(...)

\vspace{\stretch{1}}

_Art. 10 Travail de maturité_

Chaque élève doit effectuer, seul ou en équipe, un travail autonome d'une certaine importance. Ce travail fera l'objet d'un texte ou d'un commentaire rédigé et d'une présentation orale.

\vspace{\stretch{1}}

_Art.15 Notes de maturité et évaluation du travail de maturité_

(...)

2. Le travail de maturité est évalué sur la base des prestations écrites et orales.

\vspace{\stretch{1}}

\clearpage

### Règlement des gymnases du 6 juillet 2016 (RGY) {-}
_[édicté par le Conseil d'État du Canton de Vaud]_

_Art.82 Travail de maturité_

1. Les élèves effectuent un travail de maturité, seuls ou en équipe, entre la 2ème etla 3ème années, selon le calendrier fixé par le directeur et les modalités fixées par le département.
2. Le travail de maturité est évalué par un jury interne qui peut, le cas échéant, s'adjoindre un expert externe, sur la base de la mise en œuvre du projet, du document écrit déposé et de la présentation orale.
3. Le travail de maturité donne lieu à une note annuelle en 3ème année.
4. Le titre du travail de maturité est mentionné sur le certificat de maturité gymnasiale.
5. L'élève qui répète la 3ème année choisit, pour le début de l'année scolaire, soit de conserver sa note, soit d'effectuer un nouveau travail de maturité. Dans ce dernier cas, la note attribuée au premier travail n'est pas conservée.

(...)