# Attribution des salles {-}

| Thème                                                                                                         | Salle n° |
| :------------------------------------------------------------------------------------------------------------ | :------: |
| Le conte écrit transposé au cinéma                                                                            |   122    |
| Réécriture de contes                                                                                          |   123    |
| Un conte et des conteurs                                                                                      |   123    |
| Journaux (littérature personnelle)                                                                            |   126    |
| Réalité et fiction : comment certains motifs historiques se retrouvent-ils dans la littérature fictionnelle ? |   126    |
| Les machines et la communication : outils et sensibilités                                                     |   128    |
| Représentations des figures héroïques (ou non) dans les bandes dessinées (DC, Marvel, mangas ...)             |   145    |
| Élaboration d'un guide de voyage dans une ville germanophone                                                  |   141    |
| Analyse comparative et/ou création                                                                            |   146    |
| À la découverte des coulisses                                                                                 |   146    |
| Le récit de voyage                                                                                            |   139    |
| Multiculturalité et langage                                                                                   |   130    |
| Les nombres remarquables                                                                                      |   220    |
| La géométrie non euclidienne                                                                                  |   221    |
| Les défis de l'alimentation                                                                                   |   205    |
| Étude de la biodiversité                                                                                      |   205    |
| L'intelligence artificielle est-elle vraiment intelligente ?                                                  |   203    |
| Santé et sport                                                                                                |   203    |
| Le sommeil                                                                                                    |   203    |
| Des analyses chimiques avec mon téléphone portable                                                            |   212    |
| Chimie et photographie                                                                                        |   212    |
| L'eau chaude gèle-t-elle plus vite que l'eau froide ?                                                         |   212    |
| Les additifs en cosmétiques                                                                                   |   214    |
| Fluorescence et phosphorescence                                                                               |   217    |
| C'est pas sorcier                                                                                             |   119    |
| Changement climatique et sociétés                                                                             |   201    |
| L'équilibre entre la vie professionnelle et la vie privé des jeunes adultes                                   |   220    |
| Le droit dans l'univers d'Harry Potter                                                                        |   221    |
| Philosophie de l'art : La beauté et la vérité                                                                 |   224    |
| Au-delà de l'humain : transhumanisme et intelligence artificielle, quelles représentations et quels enjeux ?  |   245    |
| Le jeu vidéo : fiction ou réalité ?                                                                           |   244    |
| Ecritures d'artistes, histoire d'écritures : évolutions et appropriations de l'écriture                       |   240    |
| Composition et Réalisation d'un EP / clip vidéo musical                                                       |   310    |
| Organisation d'un concert public                                                                              |   310    |